server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inderdumpa/config-repo.git
          clone-on-start: true
          username: inderdumpa
          password: pwd
  security:
    user:
      name: root
      password: i6k4d7
  application:
    name: config-server
